### ISSUE TITLE
Select namespace of converted releases

### ISSUE THREAD

**Issue by barmic** [helm/helm-2to3#225]
Hi,

When I convert my releases from helm2 with tiller, the plugin puts it to `default` namespace instead of namespace of deployment.

When I send `kubectl config view --minify`, I have:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://10.0.0.1:443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: env-dev
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

But after conversion, my releases are created in `default` namespace. If I correctly understand the best practice I should put my release in the same namespace where my software is installed? Is it possible to put converted releases in another namespace or move them after conversion? I want to avoid reinstalling my release and it's why this plugin seems useful.

Thank you for this plugin and for your help
